// The APK's WebView origin (https://localhost, per capacitor.config.ts) has no
// server of its own, and createServerFn's client stub only gets generated by
// the TanStack Start Vite plugin, which the Capacitor build doesn't run — so
// native code can't call server functions directly. Routes under src/server.ts
// that need to be reachable from the APK (or called with an absolute URL for
// any other reason) are plain REST endpoints on this same deployed backend.
// Update this if the production domain changes (e.g. once a custom domain is set up).
export const DEPLOYED_ORIGIN = "https://tanstack-start-app.sangathsupport.workers.dev";
