import { Capacitor } from "@capacitor/core";
import { RecaptchaVerifier, signInWithPhoneNumber, type ConfirmationResult } from "firebase/auth";
import { firebaseAuth } from "@/integrations/firebase/client";
import { FirebasePhoneAuth } from "@/integrations/firebase/native-phone-auth";
import { supabase } from "@/integrations/supabase/client";
import { bridgeFirebasePhoneLogin, type BridgeResult } from "@/lib/phone-auth.functions";

// The APK's WebView origin (https://localhost, per capacitor.config.ts) has no
// server of its own — bridgeFirebasePhoneLogin's createServerFn client stub only
// gets generated by the TanStack Start Vite plugin, which the Capacitor build
// doesn't run, so it can't be called from native. This is our own deployed
// backend's plain REST equivalent instead (src/server.ts's PHONE_AUTH_BRIDGE_PATH).
// Update this if the production domain changes (e.g. once a custom domain is set up).
const DEPLOYED_ORIGIN = "https://tanstack-start-app.sangathsupport.workers.dev";

async function callPhoneAuthBridge(idToken: string, createUser: boolean): Promise<BridgeResult> {
  const response = await fetch(`${DEPLOYED_ORIGIN}/api/phone-auth-bridge`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ idToken, createUser }),
  });
  if (!response.ok) {
    return { ok: false, reason: "invalid_token" };
  }
  return response.json();
}

/** India-only for v1: 10 digits, starting 6-9 (matches TRAI mobile numbering). */
const indianMobilePattern = /^[6-9]\d{9}$/;

export function isValidIndianMobile(digits: string) {
  return indianMobilePattern.test(digits.trim());
}

export function toE164India(digits: string) {
  return `+91${digits.trim()}`;
}

/**
 * Checks registration before ever calling Firebase, so an SMS is never spent
 * on a signup that would just be rejected as a dupe, or a login for a number
 * with no account — mirrors `email_registered` / `shouldCreateUser: false`.
 *
 * `phone_registered` predates the last `supabase gen types` run, hence the cast.
 */
export async function isPhoneRegistered(e164Phone: string): Promise<boolean> {
  const { data, error } = await supabase.rpc(
    "phone_registered" as never,
    {
      check_phone: e164Phone,
    } as never,
  );
  if (error) throw error;
  return Boolean(data);
}

/**
 * Binds an invisible reCAPTCHA to a container the caller mounts. Web only — the
 * APK uses the native plugin instead (see sendPhoneOtp), which never needs one.
 * Not cached at module scope: each login/signup route mount owns its own
 * instance (via `useRef`) and must call `.clear()` on unmount, since a cached
 * verifier would otherwise point at a DOM node from a route the SPA already left.
 */
export function createRecaptchaVerifier(containerId: string): RecaptchaVerifier | null {
  if (Capacitor.isNativePlatform()) return null;
  return new RecaptchaVerifier(firebaseAuth, containerId, { size: "invisible" });
}

/**
 * Opaque handle to an in-flight phone verification, produced by `sendPhoneOtp`
 * and consumed by `verifyPhoneOtpAndSignIn`. Callers should not inspect `kind`
 * themselves except to special-case "native-auto" (see below) — everything
 * else about how the two platforms differ stays inside this module.
 */
export type PhoneAuthSession =
  | { kind: "web"; confirmation: ConfirmationResult }
  | { kind: "native"; verificationId: string }
  // Play Integrity (or SMS auto-read) verified the device instantly, with no
  // code for the user to enter at all — `idToken` is already a signed-in
  // credential. Callers must check for this right after `sendPhoneOtp` and
  // skip straight to `verifyPhoneOtpAndSignIn` instead of showing a code step.
  | { kind: "native-auto"; idToken: string };

/**
 * Sends a 6-digit SMS code to an E.164 number.
 *
 * On the APK this goes through the native Firebase Android SDK (FirebasePhoneAuthPlugin),
 * which verifies the app via Play Integrity instead of a web reCAPTCHA challenge — the JS
 * SDK's invisible reCAPTCHA can't get storage access inside our embedded WebView (Android's
 * storage-partitioning blocks the third-party recaptcha.google.com iframe, with no browser
 * chrome to grant it; confirmed via logcat showing "requestStorageAccess: Permission denied"
 * with no request ever reaching Firebase). The web build keeps using the JS SDK, where a real
 * browser tab can satisfy that challenge.
 */
export async function sendPhoneOtp(
  e164Phone: string,
  verifier: RecaptchaVerifier | null,
): Promise<PhoneAuthSession> {
  if (Capacitor.isNativePlatform()) {
    const result = await FirebasePhoneAuth.sendCode({ phoneNumber: e164Phone });
    return result.autoRetrieved
      ? { kind: "native-auto", idToken: result.idToken }
      : { kind: "native", verificationId: result.verificationId };
  }
  if (!verifier) throw new Error("Missing reCAPTCHA verifier for web phone sign-in.");
  const confirmation = await signInWithPhoneNumber(firebaseAuth, e164Phone, verifier);
  return { kind: "web", confirmation };
}

export interface PhoneAuthResult {
  data: { session: Awaited<ReturnType<typeof supabase.auth.getSession>>["data"]["session"] };
  error: { message: string } | null;
}

/**
 * Confirms the SMS code (proving phone ownership), bridges that proof to a
 * Supabase-issued sign-in code via `bridgeFirebasePhoneLogin`, then redeems it
 * the same way the email flow redeems its emailed code — so both paths end at
 * the same `supabase.auth.verifyOtp` call and the same session shape.
 *
 * `code` is ignored for a "native-auto" session — there was never a code to enter.
 */
export async function verifyPhoneOtpAndSignIn(
  session: PhoneAuthSession,
  code: string,
  createUser: boolean,
): Promise<PhoneAuthResult> {
  let idToken: string;
  try {
    if (session.kind === "native-auto") {
      idToken = session.idToken;
    } else if (session.kind === "native") {
      const result = await FirebasePhoneAuth.confirmCode({
        verificationId: session.verificationId,
        code: code.trim(),
      });
      idToken = result.idToken;
    } else {
      const credential = await session.confirmation.confirm(code.trim());
      idToken = await credential.user.getIdToken();
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : "Incorrect verification code.";
    return { data: { session: null }, error: { message } };
  }

  const bridged = Capacitor.isNativePlatform()
    ? await callPhoneAuthBridge(idToken, createUser)
    : await bridgeFirebasePhoneLogin({ data: { idToken, createUser } });

  if (!bridged.ok) {
    const message =
      bridged.reason === "not_registered"
        ? "No account found for this number. Please sign up first."
        : "Something went wrong. Please try again.";
    return { data: { session: null }, error: { message } };
  }

  const { data, error } = await supabase.auth.verifyOtp({
    email: bridged.email,
    token: bridged.otp,
    type: "email",
  });
  return { data: { session: data.session }, error: error ? { message: error.message } : null };
}
