-- Seed data for local development only.
--
-- Intentionally empty. This file previously held eight FICTIONAL facilities
-- carried over from the Lovable prototype (invented names, phone numbers and
-- websites). They were removed because seeded placeholder data is
-- indistinguishable from real listings once it reaches members.
--
-- The community directory, events and sponsors are now entered through the
-- in-app admin console (/admin) by an administrator.
--
-- If you add fixtures here for local testing, keep them obviously fake
-- ("TEST Hospital", "+91 00000 00000") and never push them to production.
