import "./lib/error-capture";

import { consumeLastCapturedError } from "./lib/error-capture";
import { renderErrorPage } from "./lib/error-page";
import { bridgePhoneLoginCore, type BridgeInput } from "./lib/phone-auth.functions";

// The APK has no server of its own (see android/app/src/main/java/.../async-hooks
// shim and vite.capacitor.config.ts), so it can't use bridgeFirebasePhoneLogin's
// createServerFn client stub — that stub only gets generated by the TanStack Start
// Vite plugin, which the Capacitor build doesn't run, so calling it there would
// inline the whole handler (service-role Supabase calls included) into the WebView
// instead of running on a server. This plain route gives the native app a normal
// REST endpoint for the same operation instead. CORS is scoped to the Capacitor
// WebView's fixed origin (https://localhost, per capacitor.config.ts) — the Firebase
// ID token itself is what's actually verified, this endpoint has no other secret to
// protect from a wider origin.
const PHONE_AUTH_BRIDGE_PATH = "/api/phone-auth-bridge";
const CAPACITOR_ORIGIN = "https://localhost";

function withCors(response: Response): Response {
  response.headers.set("Access-Control-Allow-Origin", CAPACITOR_ORIGIN);
  response.headers.set("Access-Control-Allow-Methods", "POST, OPTIONS");
  response.headers.set("Access-Control-Allow-Headers", "Content-Type");
  return response;
}

async function handlePhoneAuthBridge(request: Request): Promise<Response> {
  if (request.method === "OPTIONS") {
    return withCors(new Response(null, { status: 204 }));
  }
  if (request.method !== "POST") {
    return withCors(new Response("Method Not Allowed", { status: 405 }));
  }
  try {
    const body = (await request.json()) as BridgeInput;
    const result = await bridgePhoneLoginCore(body);
    return withCors(
      new Response(JSON.stringify(result), {
        headers: { "content-type": "application/json; charset=utf-8" },
      }),
    );
  } catch (error) {
    console.error(error);
    return withCors(
      new Response(JSON.stringify({ ok: false, reason: "invalid_token" }), {
        status: 400,
        headers: { "content-type": "application/json; charset=utf-8" },
      }),
    );
  }
}

type ServerEntry = {
  fetch: (request: Request, env: unknown, ctx: unknown) => Promise<Response> | Response;
};

let serverEntryPromise: Promise<ServerEntry> | undefined;

async function getServerEntry(): Promise<ServerEntry> {
  if (!serverEntryPromise) {
    serverEntryPromise = import("@tanstack/react-start/server-entry").then(
      (m) => (m as { default?: ServerEntry }).default ?? (m as unknown as ServerEntry),
    );
  }
  return serverEntryPromise;
}

function brandedErrorResponse(): Response {
  return new Response(renderErrorPage(), {
    status: 500,
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}

function isCatastrophicSsrErrorBody(body: string, responseStatus: number): boolean {
  let payload: unknown;
  try {
    payload = JSON.parse(body);
  } catch {
    return false;
  }

  if (!payload || Array.isArray(payload) || typeof payload !== "object") {
    return false;
  }

  const fields = payload as Record<string, unknown>;
  const expectedKeys = new Set(["message", "status", "unhandled"]);
  if (!Object.keys(fields).every((key) => expectedKeys.has(key))) {
    return false;
  }

  return (
    fields.unhandled === true &&
    fields.message === "HTTPError" &&
    (fields.status === undefined || fields.status === responseStatus)
  );
}

// h3 swallows in-handler throws into a normal 500 Response with body
// {"unhandled":true,"message":"HTTPError"} — try/catch alone never fires for those.
async function normalizeCatastrophicSsrResponse(response: Response): Promise<Response> {
  if (response.status < 500) return response;
  const contentType = response.headers.get("content-type") ?? "";
  if (!contentType.includes("application/json")) return response;

  const body = await response.clone().text();
  if (!isCatastrophicSsrErrorBody(body, response.status)) {
    return response;
  }

  console.error(consumeLastCapturedError() ?? new Error(`h3 swallowed SSR error: ${body}`));
  return brandedErrorResponse();
}

export default {
  async fetch(request: Request, env: unknown, ctx: unknown) {
    if (new URL(request.url).pathname === PHONE_AUTH_BRIDGE_PATH) {
      return handlePhoneAuthBridge(request);
    }
    try {
      const handler = await getServerEntry();
      const response = await handler.fetch(request, env, ctx);
      return await normalizeCatastrophicSsrResponse(response);
    } catch (error) {
      console.error(error);
      return brandedErrorResponse();
    }
  },
};
